# Question 1
## Level 1
**Question:** Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.

**Hints:** Consider use range(#begin, #end) method

**Solution:**

In [6]:
l=[]
for i in range(2000,3201):
    if (i%7==0) and (i%5!=0):
        l.append(str(i))
print(','.join(l))

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


# Question 2
## Level 1
**Question:** Write a program which can compute the factorial of a given numbers. The results should be printed in a comma-separated sequence on a single line. Suppose the following input is supplied to the program: 8 Then, the output should be: 40320

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [7]:
from math import factorial
n=int(input())
print(factorial(n))

6
720


# Question 3
## Level 1
**Question:** With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included). and then the program should print the dictionary. Suppose the following input is supplied to the program: 8 Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input. Consider use dict()

**Solution:**

In [8]:
n=int(input())
d=dict()
for i in range(1,n+1):
    d[i]=i*i
print(d)

10
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


# Question 4
## Level 1
**Question:** Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number. Suppose the following input is supplied to the program: 34,67,55,33,12,98 Then, the output should be: ['34', '67', '55', '33', '12', '98'] ('34', '67', '55', '33', '12', '98')

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input. tuple() method can convert list to tuple

**Solution:**

In [9]:
l=input().split(',')
print(l)
print(tuple(l))

34,67,55,33,12,98
['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')


# Question 5
## Level 1

**Question:** Define a class which has at least two methods: getString: to get a string from console input printString: to print the string in upper case. Also please include simple test function to test the class methods.

**Hints:** Use init method to construct some parameters

**Solution:**

In [10]:
class InputOutString(object):
    
    def __init__(self):
        self.s=""
        
    def getString(self):
        self.s=input()
    
    def printString(self):
        print(self.s.upper())
        
strObj=InputOutString()
strObj.getString()
strObj.printString()

Hello world!
HELLO WORLD!


# Question 6
## Level 2

**Question:** Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H] Following are the fixed values of C and H: C is 50. H is 30. D is the variable whose values should be input to your program in a comma-separated sequence. Example Let us assume the following comma separated input sequence is given to the program: 100,150,180 The output of the program should be: 18,22,24

**Hints:** If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26) In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [11]:
import math
l = [100,150,180]
q = []
for i in l:
    q.append(str(int(math.sqrt((2*50*i)/30))))
print(','.join(q))

18,22,24


# Question 7
## Level 2

**Question:** Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j. Note: i=0,1.., X-1; j=0,1,¡­Y-1. Example Suppose the following inputs are given to the program: 3,5 Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

**Hints:** Note: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.

**Solution:**

In [12]:
import numpy as np
items=[int(x) for x in input().split(',')]
x=items[0]
y=items[1]
da=np.arange(x*y).reshape(x,y)
for i in range(x):
    for j in range(y):
        da[i][j]=i*j
print(da)

4,6
[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]]


# Question 8
## Level 2

**Question:** Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically. Suppose the following input is supplied to the program: without,hello,bag,world Then, the output should be: bag,hello,without,world

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [13]:
s=[x for x in input().split(',')]
s.sort()
print(','.join(s))

without,hello,bag,world
bag,hello,without,world


# Question 9
## Level 2

**Question:** Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized. Suppose the following input is supplied to the program: Hello world Practice makes perfect Then, the output should be: HELLO WORLD PRACTICE MAKES PERFECT

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [14]:
print(input().upper())

Hello world Practice makes perfect 
HELLO WORLD PRACTICE MAKES PERFECT 


**Another solution:**

In [15]:
lines=[]
while True:
    s=input()
    if s:
        lines.append(s.upper())
    else:
        break;
for sentence in lines:
    print(sentence)

Hello world Practice makes perfect 

HELLO WORLD PRACTICE MAKES PERFECT 


# Question 10
## Level 2

**Question:** Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically. Suppose the following input is supplied to the program: hello world and practice makes perfect and hello world again Then, the output should be: again and hello makes perfect practice world

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input. We use set container to remove duplicated data automatically and then use sorted() to sort the data.

**Solution:**

In [16]:
print(' '.join(sorted(set([word for word in input().split(' ')]))))

hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


# Question 11
## Level 2

**Question:** Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence. Example: 0100,0011,1010,1001 Then the output should be: 1010 Notes: Assume the data is input by console.

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [17]:
values = [number for number in input().split(',')]
result=[]
for number in values:
    number_p=int(number,2)
    if not number_p%5:
        result.append(number)
print(','.join(result))

0100,0011,1010,1001
1010


# Question 12
## Level 2

**Question:** Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. The numbers obtained should be printed in a comma-separated sequence on a single line.

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [18]:
import math

def findEven(a,b):
    l=[]
    for i in range(a,b+1):
        s=str(i)
        if not (int(s[0])%2)|(int(s[1])%2)|(int(s[2])%2)|(int(s[3])%2):
            l.append(s)
    return l

print(','.join(findEven(1000,3000)))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888


# Question 13
## Level 2

**Question:** Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program: hello world! 123 Then, the output should be: LETTERS 10 DIGITS 3

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [19]:
sentence = input()
letters=0
digits=0
for s in sentence:
    if 64<ord(s)<91 or 96<ord(s)<123:
        letters+=1
    elif 47<ord(s)<58:
        digits+=1
print('LETTERS',letters,'DIGITS',digits)  

hello world! 123
LETTERS 10 DIGITS 3


In [20]:
sentence= input()
d={'LETTERS':0,'DIGITS':0}
for s in sentence:
    if s.isalpha():
        d['LETTERS']+=1
    elif s.isdigit():
        d['DIGITS']+=1
print('LETTERS',d['LETTERS'],'DIGITS',d['DIGITS'])

hello world! 123
LETTERS 10 DIGITS 3


# Question 14
## Level 2

**Question:** Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters. Suppose the following input is supplied to the program: Hello world! Then, the output should be: UPPER CASE 1 LOWER CASE 9

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [21]:
sentence= input()
d={'UPPER CASE':0,'LOWER CASE':0}
for s in sentence:
    if s.isupper():
        d['UPPER CASE']+=1
    elif s.islower():
        d['LOWER CASE']+=1
print('UPPER CASE',d['UPPER CASE'],'LOWER CASE',d['LOWER CASE'])

Hello world!
UPPER CASE 1 LOWER CASE 9


# Question 15
## Level 2

**Question:** Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a. Suppose the following input is supplied to the program: 9 Then, the output should be: 11106

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [22]:
a=int(input())
aa=a*11
aaa=a*111
aaaa=a*1111
print(a+aa+aaa+aaaa)

9
11106


In [23]:
a=input()
n1=int('%s'%a)
n2=int('%s%s'%(a,a))
n3=int('%s%s%s'%(a,a,a))
n4=int('%s%s%s%s'%(a,a,a,a))
print(n1+n2+n3+n4)

9
11106


# Question 16
## Level 2

**Question:** Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers. Suppose the following input is supplied to the program: 1,2,3,4,5,6,7,8,9 Then, the output should be: 1,3,5,7,9

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [24]:
print(','.join([str(int(n)*int(n)) for n in input().split(',') if int(n)%2]))

1,2,3,4,5,6,7,8,9
1,9,25,49,81


# Question 17
## Level 2

**Question:** Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following: D 100 W 200

D means deposit while W means withdrawal. Suppose the following input is supplied to the program: D 300 D 300 W 200 D 100 Then, the output should be: 500

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solution:**

In [28]:
netAmount = 0
while True:
    s = input()
    if not s:
        break
    values = s.split(" ")
    operation = values[0]
    amount = int(values[1])
    if operation=="D":
        netAmount+=amount
    elif operation=="W":
        netAmount-=amount
    else:
        pass
print(netAmount)

D 300
D 300
W 200
D 100

500


In [1]:
netAmount = 0
while True:
    s = input()
    if not s:
        break
    values = s.split(" ")
    for i in range(len(values)):
        if values[i]=="D":
            netAmount+=int(values[i+1])
        elif values[i]=="W":
            netAmount-=int(values[i+1])
        else:
            pass
        i+=2
print(netAmount)

D 300 D 300 W 200 D 100

500


# Question 18
## Level 3

**Question:** A website requires the users to input username and password to register. Write a program to check the validity of password input by users. Following are the criteria for checking the password:

1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
3. At least 1 letter between [A-Z]
4. At least 1 character from [$#@]
5. Minimum length of transaction password: 6
6. Maximum length of transaction password: 12 Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma. Example If the following passwords are given as input to the program: ABd1234@1,a F1#,2w3E*,2We3345 Then, the output of the program should be: ABd1234@1

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input.

**Solutions:**

In [42]:
pw=''.join(input().split(' '))
if len(pw)<6:
    print('too short')
elif len(pw)>12:
    print('too long')
b1=False
b2=False
b3=False
for s in pw:
    b1 = b1 | s.isalpha()
    b2 = b2 | s.isdigit()
    b3 = b3 |(s=='$')|(s=='#')|(s=='@')
if not b1:
    print('no alpha')
if not b2:
    print('no digit')
if not b3:
    print('no $#@')
    

sapodufsopdf-9879087
too long
no $#@


# Question 19
## Level 3

**Question:** You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is: 
1. Sort based on name; 
2. Then sort based on age; 
3. Then sort by score. 

The priority is that name > age > score.
If the following tuples are given as input to the program: Tom,19,80 John,20,90 Jony,17,91 Jony,17,93 Json,21,85
Then, the output of the program should be: [('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

**Hints:** In case of input data being supplied to the question, it should be assumed to be a console input. We use itemgetter to enable multiple sort keys.

**Solutions:** from operator import itemgetter, attrgetter

In [60]:
from operator import itemgetter

l = []
while True:
    s = input()
    if not s:
        break
    l.append(tuple(s.split(' ')))
    
print(sorted(l, key=itemgetter(0,1,2)))

Tom,19,80 John,20,90 Jony,17,91 Jony,17,93 Json,21,85

[('Tom,19,80', 'John,20,90', 'Jony,17,91', 'Jony,17,93', 'Json,21,85')]


In [59]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

